"""init

Revision ID: 5876f05ee8b8
Revises:
Create Date: 2023-09-13 08:27:18.130200

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.schema import CreateSchema  # , DropSchema

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5876f05ee8b8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(CreateSchema("msm", if_not_exists=True))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("otp_enabled", sa.Boolean(), nullable=False),
        sa.Column("otp_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "incorrect_login_latest",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.Column("incorrect_login_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
        schema="msm",
    )
    op.create_table(
        "secrets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="msm",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("otp_id", sa.UUID(), nullable=False),
        sa.Column("aid", sa.UUID(), nullable=False),
        sa.Column("started", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("incorrect_login_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("otp_id"),
        schema="msm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions", schema="msm")
    op.drop_table("secrets", schema="msm")
    op.drop_table("accounts", schema="msm")
    # ### end Alembic commands ###

    # op.execute(DropSchema("msm"))
